import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import { Inter } from 'next/font/google';
import { ToastContainer, Zoom } from 'react-toastify';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import BlogsState from '@/context/blogsContext';
import IsLoggedInState from '@/context/isLoggedInContext';
import IsSpinnerState from '@/context/isSpinnerContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'iBlog - A Public Blog App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className={inter.className}>
        <BlogsState>
          <IsLoggedInState>
            <IsSpinnerState>

              <ToastContainer
                position="top-left"
                autoClose={3000}
                transition={Zoom}
                hideProgressBar={false}
                newestOnTop={true}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="colored"
              />

              <Navbar />
              {children}
              <Footer />

            </IsSpinnerState>
          </IsLoggedInState>
        </BlogsState>
      </body>
    </html>
  );
}
